### PR TITLE
[DEFCONFIG] [9.12.r1] Enable Wireless Charging, add WiFi configuration

### PR DESCRIPTION
**Pull request by kholk**
Enable drivers for FM radio and Wireless Charging.

### CODE REVIEW

**Comment by MarijnS95** [comment]
Ouch, this patch conflicts with #91.

Can you push the missing `CONFIG_RADIO_ADAPTERS` there, and leave this PR for wireless charging?

**Comment by kholk** [comment]
oh wow... now THAT'S being messy :D

**Comment by kholk** [comment]
PR fixed :))

**Comment by MarijnS95** [comment]
> now THAT'S being messy

Yeah, definitely!

:smiling_imp:

**Pull request merged**
